# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- '*'

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  buildProjects: 'WebApp/*.csproj'
  unitTest: 'WebApp*[Tt]est/*.csproj'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(buildProjects)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(buildProjects)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '$(unitTest)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: WebApp
  condition: succeededOrFailed()

- task: AzureWebApp@1
  displayName: Deploy Azure Web App
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription (13d31264-17e6-4ba7-9ee8-6fdc87d6a4ee)'
    appName: 'webappwithdatabase-demo'
    package: $(System.DefaultWorkingDirectory)/**/*.zip    

