# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- '*'

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  inputs: 
    version: 3.0.x
  displayName: 'Install .Net SDK 3.0.x'

- task: UseDotNet@2
  inputs:
    version: 2.2.x
    packageType: runtime
  displayName: 'Install .Net SDK 2.2.x'


- task: DotNetCoreCLI@2
  displayName: Restore
  inputs: 
     command: restore
     projects: 'WebApp/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs: 
     command: build
     projects: 'WebApp/*.csproj'
     arguements: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
     command: test
     projects: '**Test/*.csproj'
     arguements: '--configuration $(buildConfiguration)'
     publishTestResults: true
